### ISSUE TITLE
Nice Headings for the Table View

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/epi-lab-client#42] opened 2018-02-22 13:54 UTC
As a portal user I want to have human readable headings

developer note: create a mapping between JSON-parameters and Header (see https://mibi-portal.bfr.bund.de/validate_dt.jsp)

**Comment by dptolle** [comment] 2018-03-14 14:16
Duplicate of #44

**Closed by dptolle** 2018-03-14 14:16 UTC
Labels: Discarded, Duplicate, Story
